networks:
  videoteka:

volumes:
  db-data:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - videoteka

  server:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - database
    networks:
      - videoteka

  database:
    image: mysql:8.0
    ports:
      - ${FORWARD_DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - videoteka